### ISSUE TITLE
Infer node version from package.json

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#101]
.node-version is somewhat redundant to package.json, which is more appropriate for specifying node versions. Could nodenv infer versions from this file, superceding .node-version?

**Comment by jasonkarns** [comment]
> more appropriate for specifying node versions

This varies wildly between the role of the node project. Apps typically need to specify an _exact_ version for the runtime they are deployed against. The package.json `engine` field _could_ work for this, though it's designed to specify a range of versions that the project supports.

However, libraries should be run against multiple versions of node as they are typically authored to support multiple runtimes. Reiterating the above, the package.json engines field is intended to specify a _range_ of versions on which the library is supported.

`.node-version` should be a specific version of node that the author wishes to have selected, not a range. (What does it even mean to activate a _range_ of nodes, since only one can actually be selected at a time? Choose the highest version installed? The lowest version? Any random version that matches the range?) Thus the use cases between package.json#engines and .node-version overlap quite a bit, but are marginally orthogonal depending on whether the project is an app or a library.

There is a [plugin](https://github.com/nodenv/nodenv-package-json-engine) that does indeed make nodenv respect (or attempt to respect) the package.json#engines field. The suitability of this plugin, then, depends on whether the project is an app or a library.

**Comment by Furgas** [comment]
I think it should choose the highest version installed. Of course reading `package.json` should be the last resort, so you will still be able to specify a specific version with current methods.

Unfortunately the mentioned plugin won't pick up a version to install with `nodenv install`.
