### ISSUE TITLE
nodenv: which: command not found

### ISSUE THREAD

**Issue by kinsomicrote** [nodenv/nodenv#102]
I recently upgraded from 8.0.0 to 8.9.4 using nodenv. Each time I open a new working directory from my terminal, I get the prompt,

```
nodenv: which: command not found

The `which' command exists in these Node versions:
  8.0.0
```
What could be the issue?

I should add that I did not run the `nodenv which` command.
The editor I am using is Visual Studio Code.

**Comment by jasonkarns** [comment]
what do you mean by "open a new working directory"? You mean each time you open a new shell? Or do you get this at every prompt? (If the former, it's likely something in your bashrc or bash_profile that's triggering nodenv. If the latter, it's probably a PS1 prompt or something trying to display the nodenv version.)

But more concerning is why you have a `which` binary installed under a node version. Can you trace down where the `which` bin is coming from that's in your path?

(ie, `ls -l $(NODENV_VERSION=8.9.0 nodenv which which)`

**Comment by kinsomicrote** [comment]
@jasonkarns I get the prompt when I do something like this;
```
cd react-app
code .
```
Not when I open a new shell.

I ran the command and I got;
```
nodenv: which: command not found

The `which' command exists in these Node versions:
  8.0.0

total 688
drwxr-xr-x   5 jioke jioke   4096 Mar 21 16:39 build
drwxr-xr-x 946 jioke jioke  36864 Mar 21 12:58 node_modules
-rw-r--r--   1 jioke jioke    740 Mar 23 12:56 package.json
drwxr-xr-x   4 jioke jioke   4096 Mar 23 12:56 public
-rw-r--r--   1 jioke jioke 119087 Feb 14 14:14 README.md
drwxr-xr-x   2 jioke jioke   4096 Mar 23 13:08 src
-rw-r--r--   1 jioke jioke 259612 Mar  2 11:40 yarn-error.log
-rw-r--r--   1 jioke jioke 261800 Mar 23 12:56 yarn.lock
```

**Comment by jasonkarns** [comment]
So if I'm understanding correctly, the error occurs when you run `code .`, not when changing directories, right? So the issue is that `code` is attempting to invoke `which` which has been stubbed by nodenv. (The "new directory" doesn't sound relevant because there's no error when you switch directories. And presumably, if you ran `code .` a second time, you'd get the same error a second time.)

But again, as noted in the comment above, the real problem here is that you shouldn't have a binstub for `which`. You need to track down why `which` has been installed under a node version.

> But more concerning is why you have a which binary installed under a node version. Can you trace down where the which bin is coming from that's in your path?

> (ie, ls -l $(NODENV_VERSION=8.9.0 nodenv which which)

> Separately, if nodenv which fails while under node 8.9 (or anything other than 8.0.0) then it sounds like nodenv isn't installed properly and doesn't have all its subcommands on $PATH as it should.

**Comment by jasonkarns** [comment]
Closing as stale
