### ISSUE TITLE
Why is the version number not arranged in sequence ?

### ISSUE THREAD

**Issue by sptndc** [nodenv/nodenv#103]
When I run the command `nodenv versions` and output like this:

~~~sh
$ nodenv versions    
  system
  8.10.0
  8.2.1
  8.9.3
* 8.9.4 (set by /home/sptndc/.nodenv/version)
~~~

Why the output is not like this ?:

~~~sh
$ nodenv versions    
  system
  8.2.1
  8.9.3
* 8.9.4 (set by /home/sptndc/.nodenv/version)
  8.10.0
~~~

**Comment by jasonkarns** [comment]
The output of that command is essentially an `ls` on the `$(nodenv root)/versions` directory, so it's sorted lexically.

**Comment by sptndc** [comment]
Why not set up like `nodenv install --list` ?

**Comment by jasonkarns** [comment]
That would be an improvement. The main reason why it isn't like that now is because the `install` command is provided by a plugin (node-build). It's not core nodenv.

node-build itself already has a lot of logic for parsing version numbers and that logic would need duplicated into core to leverage it. (though would be nice)

If you want to take a stab at porting that logic into nodenv-versions, a PR would be welcome. (And would likely result in a PR upstream to rbenv as well. Indeed, it might be worthwhile seeing if there are existing discussions or PRs for this issue on rbenv itself.)

**Comment by sptndc** [comment]
Yes, because it will make it look more presentable.

**Comment by jasonkarns** [comment]
see https://github.com/rbenv/rbenv/issues/1086 and https://github.com/rbenv/rbenv/pull/1111
