### ISSUE TITLE
Node complaining about mismatched binaries

### ISSUE THREAD

**Issue by j0hnm4r5** [nodenv/nodenv#108]
I get the following error message every time I run a node command:

```
npm WARN lifecycle The node binary used for scripts is /Users/$USERNAME/.nodenv/shims/node but npm is using /usr/local/Cellar/node/10.10.0/bin/node itself. 
Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```
Nothing seems adversely affected, and running `which node` and `which npm` both return paths within `/Users/$USERNAME/.nodenv/shims/`.

**Comment by jasonkarns** [comment]
Yep, this is a known issue. The shims in nodenv just delegate their calls to the appropriate bin based on the version that is chosen.

Potential fix is for the npm shim to include the option as mentioned in the warning message, but I'm not sure I really like that approach. (It would require forking nodenv's shim creation logic specifically for npm.)

**Comment by jasonkarns** [comment]
Best workaround: configure the `scripts-prepend-node-path` npm setting:

```
npm config set scripts-prepend-node-path auto
```

As the docs state, this feature of npm is about whether the current node executable matches the one that invoked npm. nodenv uses a shim to determine which executable to use. Thus, the node executable first in the path for any npm scripts is nodenv's shim. If you currently don't have a node version selected by nodenv, then the node executable that is running npm is your `system` node (typically one installed separately from nodenv, like through homebrew or your OS). ergo, mismatch

https://docs.npmjs.com/misc/config#scripts-prepend-node-path

The options for this setting are:
- `false` never prepend the "actual" node executable to `PATH`
- `true` always prepend the "actual" node executable to `PATH`
- `auto` only prepend the "actual" node executable to `PATH` if mismatch
- `warn-only` same as false, but issue the annoying warning message if mismatch

Any of the options (besides `warn-only`) will work to silence the message.

`false` is safe to use if you are confident that npm and node will both run through the nodenv shims and resolve to your `system` node. This is a safe assumption if using a recommended installation of nodenv where nodenv's shims are first in `PATH`.

`true` is safe to use if you're okay with the fact that any node invocation from your scripts will bypass nodenv and will use the node executable resolved by npm. This should also be fine since the one the npm resolves to should always be the same node that nodenv _would_ have resolved to. (Remember, nodenv's npm and node shims both resolve to the same node installation.)

`auto` is really just the same as `true`, but should only need to prepend the PATH whenever you don't have a nodenv version selected.

Personally, I recommend `auto`. The only time I can imagine where this configuration option isn't safe is if, somehow, you invoke an npm executable that _isn't_ nodenv's shim, but the node first in PATH is nodenv's shim.

**Comment by jasonkarns** [comment]
Documented workaround in FAQ: https://github.com/nodenv/nodenv/wiki/FAQ#npm-warning-about-mismatched-binaries
