### ISSUE TITLE
Can we cut another release?

### ISSUE THREAD

**Issue by cornfeedhobo** [nodenv/nodenv#111]
It's been over a year since the last github release. Can one be put out?

**Comment by jasonkarns** [comment]
What's missing? There aren't any new features since the last release.

**Comment by jasonkarns** [comment]
I apologize if the above comment came across as flippant...

I'm not entirely sure the underlying rationale for your question...

There are a number of open issues that haven't been resolved, but simply cutting a new release won't address them since there haven't been any changes to the codebase since the last release. Unless by "cut a new release", you actually meant "address some open issues"?

Related, that have been a few minor tweaks to rbenv upstream since our last release, but most of them were readme updates. I frequently pull changes from rbenv upstream and merge into nodenv. However, I typically do so whenever rbenv cuts a release; which also hasn't happened since _our_ last release. So I _could_ merge any of rbenv's unreleased changes but again, a cursory glance at the changes there shows very little significant change.

What I might assume to be your underlying point, is that there have been a lot of node releases since nodenv's last release? But nodenv itself does not need changes to handle recent versions of node. For one, node-build is the utility that is responsible for building/installing new versions of node. So node-build would be the tool that gets updated; and indeed, it is updated very frequently. Typically the same day or shortly thereafter any new node release.

What's the underlying concern?

**Comment by cornfeedhobo** [comment]
No problem. I didn't read it as flippant, but appreciate the second thought!

My use case is packaging for linux distros, so people don't have to install by-hand. The current top release doesn't include the newer node versions, and there is no internal command to pull updated definitions for an older install (please correct me if I am wrong).

I can also switch to packaging based on git hash + iso date, but since you are already versioning, I thought I'd bring up the option of another release first.

**Comment by cornfeedhobo** [comment]
No problem. I didn't read it as flippant, but appreciate the second thought!

You hit my reasoning exactly; a lot of node releases since the last release. Let me investigate the separation of node-build and get back to this issue. My apologies if it ends up I was just lost the whole time.

**Comment by cornfeedhobo** [comment]
Yeah, I apologize completely. I had forgotten about the separation of node-build, and see it is regularly updated. Thank you again!

**Comment by jasonkarns** [comment]
While you're looking at all this, you may be interested in https://github.com/nodenv/node-build-update-defs

https://github.com/nodenv/nodenv/wiki/FAQ#available-node-versions-are-out-of-date
