### ISSUE TITLE
systemd service example

### ISSUE THREAD

**Issue by noraj** [nodenv/nodenv#117]
I tried during hours to properly setup a systemd service using node/npm version of the user, for example:

```systemd
[Unit]
Description=Flood, web interface for rTorrent
After=network.target

[Service]
User=flood
ExecStart=npm start /srv/flood
WorkingDirectory=/srv/flood/
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

This user (flood) has `/home/flood/.nodenv/versions/10.13.0/` set as default locally and globally.

But using `/home/flood/.nodenv/versions/10.13.0/bin/npm` instead of `npm` won't do the trick because `/home/flood/.nodenv/versions/10.13.0/bin/npm`starts with `#!/usr/bin/env node` and also those two lines from the bashrc are not sourced as systemd service is not lauching a login shell:

```bash
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"
```

So my question is simple: can you give us an example of systemd service using node/npm (from nodenv of course).

**Comment by jasonkarns** [comment]
Some related background on why rbenv (and nodenv) don't _officially_ support shared multi-user installations: https://github.com/rbenv/rbenv/issues/38

What's missing from the above is that the user's shims aren't in PATH:

> There is nothing special that users need to do for system install. The steps are:
> 
> 1. Install or symlink Ruby versions under RBENV_ROOT/versions
> 2. Ensure that processes have RBENV_ROOT/shims in PATH
> 
> That's it.

https://github.com/rbenv/rbenv/issues/38#issuecomment-148413842

I'd suggest using systemd's `Environment` or `EnvironmentFile` to ensure that `RBENV_ROOT/shims` is in PATH. (keep in mind, env vars aren't expanded for these).

Alternatively, I _believe_ the only that that should be necessary is to invoke npm in the context of nodenv:

```
ExecStart=/home/flood/.nodenv/bin/nodenv exec npm start /srv/flood
```

This works (or should work) because nodenv-exec will ensure the selected node's bin directory is added to `PATH` when invoking `npm`.

**Comment by noraj** [comment]
@jasonkarns Thanks a lot, `ExecStart=/home/flood/.nodenv/bin/nodenv exec npm start /srv/flood` worked perfectly and is much more simple than what i thought.

**Comment by jasonkarns** [comment]
I would love a wiki page with an example systemd config if you have the
time :)

**Comment by noraj** [comment]
@jasonkarns Done :heavy_check_mark:  https://github.com/nodenv/nodenv/wiki/Use-nodenv-with-systemd

**Comment by jasonkarns** [comment]
@noraj thanks!

**Comment by davemo** [comment]
For anyone coming in late to the party, the wiki page link is here: https://github.com/nodenv/nodenv/wiki/Use-with-systemd
