### ISSUE TITLE
Support yarn global modules

### ISSUE THREAD

**Issue by sptndc** [nodenv/nodenv#120]
This is feature request for support yarn global modules for `rehash`, `whence`, and `which`.

**Comment by jasonkarns** [comment]
I agree with the desire, but this will be a bit tricky. Yarn (by default) insists on installing its global modules _outside_ the scope of node. That is, `~/.config/yarn/global`. Which means a yarn-installed global module is not contained to the node version that it was installed by. For modules that don't have any compilation requirements, this isn't really a problem. However, it's probably rare at this point for a global module to not have even a single dependency that requires compilation. Just a single dep with compilation will mean the module will need to be re-built each time you switch node versions. (Which isn't a problem with npm because npm's global modules are scoped to the node installation itself.)

This is _possibly_ further complicated by the fact that maybe a third of yarn installs are via `npm i -g yarn` vs homebrew (or other).

I'm not against this feature, but I imagine it will end up being low on my priority list. But I'd love a PR or even some research on what it would require to implement.

**Comment by zzyyxxww** [comment]
For those who are struggling with this
The current way to have this is to include the yarn global bins in your PATH.

[The default location for them is `$HOME/.yarn/bin`](https://yarnpkg.com/lang/en/docs/cli/global/#defining-install-location) (you can check your own bin path with `yarn global bin`).

So, you just add this to whatever your shell autoexec file is (`.bash_profile`, `.bashrc`,`.zshrc` or whatever):
```
export PATH="$HOME/.yarn/bin:$PATH"
```
And you decide if you put it above or below the `eval "$(nodenv init -)"` part.  
I put it above since I want it to make yarn global bins to take precedence over npm global bins.

**Comment by jasonkarns** [comment]
@zzyyxxww thanks for the extra tips!

Just a quick note on 

> And you decide if you put it above or below the `eval "$(nodenv init -)"` part.
> I put it above since I want it to make yarn global bins to take precedence over npm global bins.

Recall that `nodenv init -` will _prepend_ to the existing PATH (as most manual PATH adjustments do as well, via `PATH=foo:$PATH`). Which means anything you add to PATH _before_ nodenv init, will be _superseded by_ nodenv/node/npm's bins.

So if you want yarn's bins to take precedence, you should add it to PATH _after_ nodenv-init:

```sh
eval "$(nodenv init -)"
PATH=$HOME/.yarn/bin:$PATH
```
