### ISSUE TITLE
nodenv: version `v6` is not installed

### ISSUE THREAD

**Issue by jrnail23** [nodenv/nodenv#139]
(nodenv version: 1.3.0)
In a project that has both a `.node-version` file (content: `v6`) and an `.nvmrc` file (content: `6`), I'm now getting `nodenv: version v6 is not installed (set by /Users/myusername/myproject/.node-version)` when I run `nodenv which node`.

I've got node `6.9.1` installed, so I'm guessing this is an issue with nodenv trying to parse the content of the `.node-version` file (`v6`).  

I'm not entirely sure if this is new or not, since I've typically also had `nodenv-nvmrc` installed, but this is the first time I've seen this issue.

**Comment by jasonkarns** [comment]
I can't be certain, since I'm not familiar with the internals of `nodenv-nvmrc`, but it would be my assumption (and hope) that `.node-version` is preferred when it exists. nvmrc and/or package.json#engines (if using nodenv-package-json-engine) should be treated as fallbacks since `.node-version` is the only file that nodenv proper reads and writes.

**Comment by jrnail23** [comment]
@jasonkarns, thanks for the reply.  I actually resolved my problem by installing `nodenv-aliases`.  For some reason, I had assumed that the `nodenv-aliases` behavior was built-in to `nodenv`.

Please feel free to close this issue, unless you see an actual bug here.
