### ISSUE TITLE
[Git Bash] nodenv init - fail

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#156]
When `nodenv init -` runs in Git Bash, then it complains:

```console
/c/Users/pen4587/.nodenv/bin/nodenv: line 1: ../libexec/nodenv: No such file or directory
```

In fact, even though my home directory is present in Git Bash PATH, `which` strangely has trouble finding nodenv. Instead, nodenv only shows up in `where`.

Latest master, Windows 10.

**Comment by jasonkarns** [comment]
I'm wagering this is because of the symlink. (`bin/nodenv` is a symlink to `libexec/nodenv`)

I'm assuming that a vanilla git-clone on windows doesn't setup (or support?) symlinks.

**Comment by jasonkarns** [comment]
nodenv doesn't officially support windows. I would like to keep this open for a while, though, in case other users are capable of digging in to see what might be necessary to allow nodenv to work on MingW.

I believe other users have had success with WSL or cygwin, though.

**Comment by jasonkarns** [comment]
Closing this under the assumption that this is due to the symlink. Presumably, the windows equivalent of a symlink will need to be made manually from clones on git-bash such that the `nodenv` bin is found in PATH and invokes the _actual_ executable which lives under libexec. (And ensures it invokes it with the correct current working directory.
