### ISSUE TITLE
POSIX compliance

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#161]
Thank you for maintaining the excellent nodenv project! Could the installer and library be rendered into pure POSIX `sh`, for compatibility with more development environments? This would automatically unlock support for:

* POSIX sh users
* ksh users
* dash users
* posh users
* ash users
* yash users
* oil shell users

**Comment by jasonkarns** [comment]
rbenv works fine in all those shells. rbenv only requires that bash be _installed_ (and on PATH); it need not be the user's shell.

There are only two commands that are dependent on the user's interactive shell:
- nodenv shell
- nodenv init

Both of these commands emit output that must be evaled by the shell in order to function. They are both rather minimal and ought to already support many (if not all) of the shells you mention above.

You can inspect their output:
- `nodenv init -`
- `nodenv sh-shell`
- `nodenv sh-shell {VERSION_NAME_HERE}`

If any of these commands do not work for your shell, you're more than welcome to submit an issue specific to the command and shell that is problematic.

More details available in this thread: https://github.com/rbenv/rbenv/issues/195
