### ISSUE TITLE
14.3.0 not found

### ISSUE THREAD

**Issue by villesau** [nodenv/nodenv#162]
Looks like Node version 14.3.0 is not found even after `brew update && brew upgrade node-build` although it's the latest version: https://nodejs.org/en/

**Comment by jasonkarns** [comment]
Definitions are provided by https://github.com/nodenv/node-build/tree/master/share/node-build, whose latest version in homebrew is 4.8.2 which doesn't include node 14.3.0.

If you desire up-to-the-minute node versions, you're better off [installing node-build via git-clone](https://github.com/nodenv/node-build#installation) so that you'll have node versions as soon as node-build has them (which is well before they are released to homebrew).

14.3.0, for instance, was available in node-build the same day it was released. https://github.com/nodenv/node-build/blob/master/share/node-build/14.3.0

**Comment by jasonkarns** [comment]
An alternative is to use the [node-build-update-defs plugin](https://github.com/nodenv/node-build-update-defs) to scrape your own definitions without waiting for them in node-build itself.

Or for one-off quick installations, you can install node manually to `$(nodenv root)/versions`

**Comment by jasonkarns** [comment]
Released: https://github.com/Homebrew/homebrew-core/pull/55263

**Comment by villesau** [comment]
Thanks for the detailed explanation @jasonkarns ! I was somehow under impression that the process is more automated so I thought there might be something wrong. Information about lagging latest versions could be nice to have in readme.
