### ISSUE TITLE
Last node build takes time to be available

### ISSUE THREAD

**Issue by vschoener** [nodenv/nodenv#165]
Hello guys,

Don't want to rush anyone, but I use renovate to manage my packages version and it also update node version. Problem is, most of the time it does it, I'm not able to run node because the build is not yet available.

Actually the version has been moved up to 12.18.2 but last version is 12.18.0.

I just wanted to understand the process to get the last version available of node, is it possible to have asap?

Thank you

**Comment by jasonkarns** [comment]
I just documented the full process, including the alternative setups and installation methods which directly impact the availability lead time. https://github.com/nodenv/node-build/wiki/Updating-Available-Definitions#the-process-for-releasing-official-definitions

There are a couple ways of decreasing this time for homebrew users (who are the most impacted) but there are tradeoffs, which is why it hasn't happened yet.
