### ISSUE TITLE
recommended way to install the latest stable version?

### ISSUE THREAD

**Issue by erjoalgo** [nodenv/nodenv#171]
What is the nodenv equivalent of `nvm install stable`?

**Comment by jasonkarns** [comment]
At present this isn't possible. Due to the way ruby-build (and therefore node-build) create versions, the definition file becomes the name of the installed version. Which would mean that a build definition named `stable` would then create a node named `stable` (which wouldn't be matched by a .node-version file that specifies a version number nor would it be automatically updated so even the name 'stable' would be a lie once a new release drops). There are a host of other complications which is why this hasn't been completed yet; but there is a tracking issue https://github.com/nodenv/node-build/issues/145
