### ISSUE TITLE
Question: how to best run globally installed npm module?

### ISSUE THREAD

**Issue by jakub-g** [nodenv/nodenv#183]
Hi, 

I know this is not exactly the main use case for nodenv (quite the contrary), but I'm wondering what is the best way to run a globally installed npm module for local dev?

Say I do `npm install -g foobar`

Assuming I'm currently using global node 16.3.0, this will make `foobar` executable available under `~/.nodenv/versions/16.3.0/bin/foobar`.

Obviously, it's not very ergonomic to run `~/.nodenv/versions/16.3.0/bin/foobar`, I'd rather prefer to do some config (modify `PATH` etc.) and run something like `foobar` or `something foobar`.

As a workaround, I could either `npx foobar` or create a bash function that does `cat ~/.nodenv/version` in subshell to locate the good folder, but I'm wondering if there's a built-in way to do just this that I missed?

**Comment by jasonkarns** [comment]
I won't hold up any of these options as "best" but I'll share a couple options.

Firstly I'll reiterate the assumption that global packages should be rare. The only packages (IMO) that should be installed globally are those that expose CLIs meant to be used _outside_ of a project. That is, generally only project scaffolding tools. CLI utilities that are used _within_ a project should generally still be added as development dependencies. Then you can add the projects `node_modules/.bin/` to your PATH (within that project) to make those CLIs available.

But to the original question...

1) One option is to install these (hopefully few) global packages in _every_ nodenv version. This is reasonable if you don't typically run a lot of different nodes, and/or you have a very limited set of global packages. There is a plugin that facilitates this flow, such that each time you install a new node, it will automatically install a list of selected global packages: https://github.com/nodenv/nodenv-default-packages

2) Another option is to install a system node outside of nodenv, and use this node for all global packages. I use this flow myself, with a node installed via homebrew. I have nodenv configured such that `system` is my default node; and all my global packages are installed via `NODENV_VERSION=system npm i -g foo`

3) There's also a third option that I think is the "correct" approach, despite it being experimental and definitely not battle-tested. The theoretically "pure" approach is that global node packages represent system utilities. As such, they should technically be managed by your system dependency manager (ie, homebrew on macOS). IMO, it's a bit of a hack for these global packages to be installed through npm. The ruby community had this same problem over a decade ago with rubygems being used to distribute "system" packages. https://github.com/sportngin/brew-gem was built as a "hack" to leverage homebrew to be the package manager, even though installation was through rubygems. I forked this and modified it to use npm, though I haven't really ironed out the kinks or "publicized" it. https://github.com/jasonkarns/brew-npm Might be worth a look.

**Comment by jakub-g** [comment]
Thanks for a detailed writeup! All options are interesting and have their advantages. I feel like option 2 is the simplest.

I feel like your writeup deserves to be added to the docs.

**Comment by michaeleisel** [comment]
What if nodenv used symlinks so that the bin directory of the current version of npm for that shell, or at least the global one, resided at some fixed path? E.g., it could exist at `shims/bin`, and then one just needs to add `~/.nodenv/shims/bin` to the path, or else have it automatically added in `nodenv init -`

**Comment by jasonkarns** [comment]
@michaeleisel If I understand you correctly, you're proposing that a single directory (`~/.nodenv/shims/bin`) point to _dynamic path_. So in that case, when the "active node" changes, the symlink would be modified to point to a different node's global modules?

A couple problems with that (assuming I interpreted the suggestion correctly):
- user has two terminals open. terminal 1 is using node 14, terminal 2 is using node 16. which one does the symlink point to? (remember, symlinks are _on disk_. they can't have different states based on environment variables)
- even if ^^ were possible to resolve, this presumes there is some hook that triggers nodenv to "switch nodes". That's not the way nodenv works. In fact, it intentionally does _not_ use hooks of any kind precisely because of their buggy nature.

rvm was notoriosly buggy and super complex because it relied on "hooking" into directory-change events to switch versions. note, bash doesn't actually have cd hooks, they are approximated by wrapping the cd builtin with a function that could then do things. wrapping builtins is brittle. Which is why rbenv was written with a different architecture: shims. Instead of pre-emptively changing environment variables when you change directories, rbenv (and hence, nodenv as its fork) does nothing! Instead, nodenv's shims (for `node`, `npm`, `npx`, etc) are first in your `PATH`. When you invoke `node`, the `node` shim invokes `nodenv` to ask "what version should be active?". nodenv at that point, consults (in order) NODE_VERSION env var, .node-version files (up ancestors to `/` root), any plugins, and finally `$(nodenv root)/version`. After it has determined which node version is active, it essentially proxies the command over to that node.

Since everything is done _at the moment you invoke the shim_, there isn't any moment in advance of that which could modify the symlink.

However, this does hit on a hint of an idea. Nodenv already shims all globally-installed modules. It's that very shim that is being invoked when you run, say, `ember`, and when nodenv resolves what node version is active, it delegates to that version's node_modules/bin/ directory. If ember isn't installed in that version, you get the error.

So let's say we write a nodenv-plugin that, _while nodenv is figuring out which node version to use_, the plugin is able to inspect what the command is (ember), and override the node version if ember isn't installed? This is only a half-thought because I'm pretty sure the current `exec` and `which` hooks short-circuit the plugins (which means the plugin might not have a chance to alter the version by the time the plugin runs). But it's been a while since I was poking at the hook code. So @michaeleisel , if you want to pull a little harder on that thread, we might have a nodenv-floating-globals plugin!
