### ISSUE TITLE
In addition to .node-version, support .tool-versions and .nvmrc

### ISSUE THREAD

**Issue by lancesnider** [nodenv/nodenv#199]
I use Nodenv, but as a freelancer I work with many teams using different tools, like NVM and and ASDF. 

- NVM uses a .nvmrc file to define the local version of node
- ASDF uses .tool-versions

Rather than creating an additional .node-version in each repo, it'd be nice if Nodenv would read the node version from .tool-versions or .nvmrc if .node-version doesn't exist.

**Comment by elstgav** [comment]
[`nodenv-nvmrc`](https://github.com/ouchxp/nodenv-nvmrc) supports this functionality for `.nvmrc`. See https://github.com/nodenv/nodenv/issues/116#issuecomment-442574008 for why this isn’t supported natively.

**Comment by lancesnider** [comment]
Yeah, that makes sense. Thanks @elstgav. I think we can call this closed.

**Comment by jasonkarns** [comment]
Related thread attempting to get nvm to support a standard `.node-version` file: https://github.com/nvm-sh/nvm/issues/794

I believe asdf supports .node-version file via options and/or configuration (or perhaps via plugin): https://asdf-vm.com/manage/configuration.html#legacy-version-file

`.ruby-version` has become a defacto standard in the ruby world, across multiple version managers. So too, `.node-version` is somewhat broadly supported.

While I obviously can't influence other projects' features, I would say that I think it's in the community's best interest to have as many tools as possible support a single standard file. (who wants to force everyone on the team to use the same tool? conversely, who wants their repo to have half a dozen different files all for ostensibly the same purpose) @shadowspawn has also done a fantastic job documenting support across tools: https://github.com/shadowspawn/node-version-usage

But also, lastly, I'll plug the https://github.com/nodenv/nodenv-package-json-engine plugin. Considering our repos already have package.json, which already contains an `engines.node` property for declaring supported runtimes, there's an argument for not even using .node-version at all 😄 . Of course, there's more nuance than that. Libraries that are intended to be installed as dependencies should generally not have a "version locking" file in their repo because as deps, they'll be run across a broad spectrum of runtime versions. By contrast, apps that have a single target deployment runtime should.

**Comment by jasonkarns** [comment]
All that to say, I definitely think it would be great to have a plugin that does read .tool-versions ;) if someone wants to whip that up.

The following plugins all do variations of the same thing and would be a great template to start from.

https://github.com/nodenv/nodenv-package-json-engine
https://github.com/ouchxp/nodenv-nvmrc
https://github.com/aripollak/rbenv-bundler-ruby-version
