### ISSUE TITLE
npm doesn't install into nodenv directory by default

### ISSUE THREAD

**Issue by felixfoertsch** [nodenv/nodenv#44]
**System:** Mac OS X El Capitan 10.11.2
**Shell:** zsh

Hey guys,

I just fiddled around with **nodenv** (installed with homebrew) and tried to install a package. Since I'm used to **rbenv**, I figured:

rbenv is for ruby; ruby package manager is gem.
nodenv is for node; node package manager is npm.

rbenv is set up so gem puts all the gems into the .rbenv folder corresponding to the version.
So I thought, nodenv does the same.

But by default, so it seems, npm install puts the node packages (do they have a name, too? like "gem"?) into the current directory. `npm install grunt` from the home directory, puts the files into ~/.npm and ~/node_modules.

I had to add the -g flag to use the ~/.nodenv folder: `npm install grunt -g`

Since I am not an expert programmer, this took a while to figure out. Is this intended behavior or do I have my system set up wrongly?

If it's not my error, might I suggest adding this info into the docs, so people not used to node and npm can find it easily?

Edit: `grunt`is now installed into `~/.nodenv/versions/5.5.0/lib/node_modules`. But it still doesn't show up in $PATH.
Edit2: Yeah, it looks like the shims somehow don't update on my machine. Really weird. Any suggestions?
```
❯ echo $PATH
/Users/felixfoertsch/.nodenv/shims:/Users/felixfoertsch/.rbenv/shims:/Users/felixfoertsch/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
```

Edit 3: Okay, I'm an idiot. For grunt to work, there is a cli tool `grunt-cli` after installing that, I can confirm that the shims DO work.

Main issue still stands with the -g flag.

**Comment by jasonkarns** [comment]
This is by design. rbenv doesn't change where rubygems go, and nodenv doesn't change where npm packages go. Ruby gems are always global in ruby but npm packages are always local by default in node. This is desired and normal for npm packages (it lets you have different versions of the same node package installed without conflicts.) npm packages always go into `node_modules/`

(The `~/.npm` directory that npm created is for configuration and cache data and that would have been created in the home directory no matter which directory you were in when you installed grunt.)

I recommend checking out npm's [documentation](https://docs.npmjs.com/all)

Regarding shims, be sure to run `nodenv rehash` after installing global packages, in order for nodenv to make shims for any newly-installed global packages. Alternatively, there is the [nodenv-package-rehash](https://github.com/nodenv/nodenv-package-rehash) plugin that will automatically call rehash when global packages are installed.
