### ISSUE TITLE
nodenv with Travis

### ISSUE THREAD

**Issue by skippednote** [nodenv/nodenv#50]
Is there an example for how to use nodenv on Travis CI?
I've tired the setup written in the README.md but that doesn't seem to work, Travis isn't detecting the nodenv binary.

**Comment by jasonkarns** [comment]
What method of setup did you follow?

**Comment by jasonkarns** [comment]
I'm not sure how to help with this. Is nodenv cloning correctly? Is it in the correct location? Does travis allow usage of binaries in `$HOME`?

Can you verify that the clone is successful and the binary is where you expect it?
Can you verify that executing the binary via absolute path succeeds?
Can you verify that your `$PATH` is correct?
Show what `which nodenv -a` emits.


Though I'd take a step back and ask why you need to install nodenv on travis since they support node via nvm out of the box.

**Comment by jasonkarns** [comment]
closing as stale. feel free to re-open with further details if you still want guidance.
