### ISSUE TITLE
WLS conflict with \r line endings

### ISSUE THREAD

**Issue by mcandre** [nodenv/nodenv#55]
When I try to build nodenv in Windows Subsystem for Linux bash, I get an error about some of the line endings:

# Trace

```
.nodenv (master)$ src/configure && make -C src
: invalid optionine 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
src/configure: line 3: $'\r': command not found
src/configure: line 5: $'\r': command not found
src/configure: line 20: syntax error near unexpected token `$'in\r''
'rc/configure: line 20: `case "$(uname -s)" in
```

# Workaround

```
$ sudo apt-get install tofrodos
fromdos libexec/*
fromdos completions/*
direnv reload
```

If I want to 100% pass-through the line endings between my local file system and the git remote, which git settings should I use? I code on both Windows and Linux, so I don't want to force my projects to either LF or CRLF, but simply respect line endings on a per-file basis.

**Comment by jasonkarns** [comment]
This is a good question. Care to open upstream against https://github.com/rbenv/rbenv? I'm not familiar with the C extension. In fact, the extension isn't strictly necessary for operation. It's merely for performance boost.

**Comment by evenicoulddoit** [comment]
This was very helpful for me, as I'd foolishly set `git config --global core.autocrlf true` within WSL (handling a folder which was symlinked from the windows filesystem, which resulted in my *rbenv* installation being messed up. The weird issue with the `set` line seemed very odd to me, and struck me as likely caused by some file ending stuff, but found reassurance in your traceback.

I didn't call `fromdos` in the end, but simply removed the global `core.autocrlf` and recloned (as rbenv is within the linux filesystem). Calling `src/configure` then worked as expected.

**Comment by jasonkarns** [comment]
👍
