### ISSUE TITLE
can't install 6.9.2...?

### ISSUE THREAD

**Issue by osher** [nodenv/nodenv#57]
Hi, 

Im using nodenv on centos, I'm trying to install 6.9.2 - but `nodenv` claims `definition not found: 6.9.2`.
(this after successfully installing 6.9.2 on windows using `nodenv`s younger brother `nodist`).

When I'm running `nodenv install --list` I'm getting such an immediate response (without 6.9.2 in it) that I don't think it's really checking for available versions on the web, but I could be mistaking...
`git pull` sais `Already up-to-date.`
Is there a local cache I should clear?

Help?

**Comment by osher** [comment]
baah. found it.

The versions list is a part of the node-build plugin, typically installed at `~/.nodenv/plugins/node-build`.

To install new versions, one must enter this folder, and `git pull`.

If there is a better / smarter / more integrated way to do that - I'd love to know.

**Comment by jasonkarns** [comment]
node-build (which is the plugin under the `nodenv install` covers) doesn't touch the web. node-build uses local definition files (for myriad intentional design reasons).

You mentioned `git pull` so I assume you installed nodenv via git clone and not via homebrew? Which means I assume you installed node-build via git clone as well? You'll need to do git-pull from node-build's directory (`$(nodenv root)/plugins/node-build`)

For any git-installed plugins, there is the `nodenv-update` plugin, which just iterates through all plugins and issues `git pull` command: https://github.com/nodenv/nodenv-update

**Comment by jasonkarns** [comment]
Ah, I see you figured it out on your own! Comment-race-condition :)

I would look into nodenv-update for keeping all nodenv plugins (including node-build) up to date. 

There is also [node-build-update-defs](https://github.com/nodenv/node-build-update-defs) plugin. Instead of updating node-build, this plugin actually scrapes nodejs.org and creates new build definition files. However, you then need to occasionally prune the scraped build defs that were created by node-build-update-defs because as node-build is updated, you'll end up with duplicate build defs (between the ones you scraped and the ones that are continually added to node-build itself).

**Comment by osher** [comment]
you do see the usability issue here...
I cant think of a configuration where `nodenv` is installed and `novenv-build` is not.
As such - I would expect a tighter integration between the two - maybe exposed as `nodenv update` - same as `apt-get update` and more equivalents.

Under the hood - `nodenv update` can run `git pull` on `node-build` or something.
