### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by rektide** [nodenv/nodenv#69]
It'd be great if install instructions were `npm install -g nodenv`. Kind missed the mark on that by a mile by not ever releasing onto npm, as someone made a different project and released it in early 2015, so you lost the name, but using some other name in package.json to make this accessible & easy to install would be great.

I am aware that this is a C project. I have plenty of non JS projects on npm, as do others. The package infrastructure ought be flexible enough to still run your existing configure and make.

Would be great to see install drastically simplified, and npm install -g really seems like the sweetest spot for that.

**Comment by jasonkarns** [comment]
A little inception-y, no?

Installing nodenv through npm would mean having a node installed first. And that's supposed to be nodenv's job (to manage installing and switching nodes). More confusingly, it would mean that nodenv would be installed _within_ a node installation. (Since the default global node modules live under `NODE_PREFIX/lib/node_modules/`) So assuming that one _did_ have a node installation available with which to install nodenv, and assuming that one wants to manage _all_ their nodes with nodenv (kinda the point), there would be a high probability of the original node being uninstalled; thus removing nodenv itself.

Given that homebrew users who install and use nodenv frequently still install a 'system' node via homebrew, I can see having a "bootstrap" node with which to install nodenv. Of course, for that scenario, homebrew users would typically use homebrew to install nodenv. ;)

For non-mac users, I suspect the idea of having nodenv itself live _under_ a node (especially one that it didn't manage) would be weird. But I could see evidence to the contrary.

How would you address the scenarios I've outlined above with regards to bootstrapping nodenv through an existing node, and dealing with nodenv living under a node?

**Comment by rektide** [comment]
Almost all Linux distributions have a Node, usually a decent one. Almost all use of nodenv is to haul out some relatively ancient version of Node.js for some neglected project that needs some old version.

I definitely had trouble installing Nodenv when node already existed on Linux. I'm not sure if this mates with your proposed nodenv within node issue or no, but it could well have.

I don't know enough about how Nodenv functions to guess at how I'd change it's implementation. It seemed odd to me that npm install -g nodenv resulted in something very unexpected happening. And just running through [alternatives](https://github.com/nodenv/nodenv/wiki/Alternatives), n, nave, node-bin, and avn all are npm installable, and I rather expected something similar.

It's fine if this is not a goal for nodenv. There are quite a number of other installers that are not themselves npm installable. I do think it'd be a great capability. I don't have any technical suggestions though for how to satisfy nodenv's expectations for where it thinks it'll find stuff. Thanks for the discussion on installation.

**Comment by jasonkarns** [comment]
Heh, I didn't realize most linux distros included node now!

The more I think about it, the more I don't think it would be a _bad_ thing to have it on npm. Our package.json is currently only there for leveraging npm for tests/build/release scripts. Since the release process is already automated, including npm-publish in the mix wouldn't be difficult...

I think we might give it a shot.

**Comment by elektronik2k5** [comment]
Great idea, +1!

**Comment by chriscarpenter12** [comment]
I don't see the point in this. I kind of get what @rektide is saying, but if this is intended to be like rbenv or pyenv (which it is) you aren't going to use your system ruby to install rbenv. You install it to manage the ruby versions. Being on npm does nothing but cause confusion. Which is the global node version now? Technically the system node is if it's managing other node versions.

**Comment by jasonkarns** [comment]
So I've decided to go ahead and publish on npm.

The deciding factor is that many of the nodenv plugins require a "local" nodenv installation or stubs for their test suites. While it's not difficult to just clone nodenv locally, it's a lot easier to include nodenv itself as a devDep for these plugins. That makes the CI build cleaner and makes it easier to validate against a range of nodenv versions and to test against pre-releases, etc.

And lastly, I suppose it wouldn't be the worst thing in the world if nodenv itself were installed on the OS or system node (eg, homebrew's node) and then separately had nodenv managing all the rest.

**Comment by jasonkarns** [comment]
https://www.npmjs.com/package/@nodenv/nodenv
