### ISSUE TITLE
`nodenv init` won't add shims to `$PATH`

### ISSUE THREAD

**Issue by ZIJ** [nodenv/nodenv#84]
I've ran the installation as in readme step-by-step (tried both homebrew and git ways) on OS X and restarted terminal, however only `~/.nodenv/bin` was added to PATH and so running `which node` would still point to /usr/local/bin/node. Figured out a fix:
```
echo 'export PATH="$HOME/.nodenv/shims:$PATH"' >> ~/.bash_profile
```
Didn't look much into detail on what's going on under the hood

**Comment by jasonkarns** [comment]
That's what nodenv init does. Was `nodenv init` not added to your bashrc?

**Comment by jasonkarns** [comment]
(see the output of `nodenv init -` to see what it does when evaled)

**Comment by martinalbion** [comment]
I had to manually edit .bash_profile on OS X High Sierra after I installed nodenv via Homebrew.  Paste these lines into .bash_profile using nano and restart your terminal.

export NODENV_ROOT="$HOME/.nodenv"
export PATH="$HOME/.nodenv/bin:$PATH"

eval "$(nodenv init -)"

The output from 'node -v' and 'npm -v' sound work after that.  It's unclear why 'nodenv init' didn't make these entries, I just copied the syntax and structure of the lines that pyenv added.

**Comment by jasonkarns** [comment]
`export PATH="$HOME/.nodenv/bin:$PATH"` doesn't need added manually because that's the first line of what `nodenv init -` does when evaled. (And `NODENV_ROOT` isn't necessary unless you're changing it to something other than the default, which doesn't appear to be the case here.)

`nodenv init` does not add this automatically. Indeed, it is nodenv's opinion that users' `.bashrc`/`.bash_profile` files should never be modified automatically by tooling. That's why the output of `nodenv init` is specifically the _instructions_:

```
# Load nodenv automatically by appending
# the following to ~/.bashrc:

eval "$(nodenv init -)"
```

**Comment by jasonkarns** [comment]
( @martinalbion sorry, I glanced too quickly and thought your `export PATH` line was adding the shims to PATH as `nodenv init -` does. nodenv itself does still need added to path somehow as you indicated)

**Comment by jasonkarns** [comment]
As this question keeps popping up, I've started a FAQ page on the wiki. https://github.com/nodenv/nodenv/wiki/FAQ#node-is-not-available
