### ISSUE TITLE
The program 'node' is currently not installed.

### ISSUE THREAD

**Issue by webmobiles** [nodenv/nodenv#87]
nodenv is working good on my mac, but in ubuntu 17 I've got on terminal:

```
node -v
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy

```

the only way to work is  with this:

`sudo ln -s $HOME/.nodenv/versions/8.3.0/bin/node /usr/bin/node`

is there a fix for that?  why is not automatic like with mac?

**Comment by martinalbion** [comment]
Take a look at your .bash_profile on your mac and compare it to .bashrc on linux.  I needed these entries for the shims to function on my mac.  Perhaps that is where your problem lies on linux.

export NODENV_ROOT="$HOME/.nodenv"
export PATH="$HOME/.nodenv/bin:$PATH"

eval "$(nodenv init -)"

**Comment by jasonkarns** [comment]
As @martinalbion noted, if you want nodenv loaded automatically, you need `eval "$(nodenv init -)"` in your `.bashrc` or `.bash_profile`. (Though the `NODENV_ROOT` isn't necessary since that's the default, and `PATH` is the first thing that modified by `eval "$(nodenv init -)"`.)

See the output of `nodenv init` for instructions on setting it up.

**Comment by jasonkarns** [comment]
As this question keeps popping up, I've started a FAQ page on the wiki. https://github.com/nodenv/nodenv/wiki/FAQ#node-is-not-available
