### ISSUE TITLE
Can nodenv manage homebrew-installed node/npm?

### ISSUE THREAD

**Issue by senorflor** [nodenv/nodenv#90]
Hi all, thanks for the work you do to provide and maintain `nodenv`: makes my days in Javascript land more pleasant and productive!

I'm wondering what you all think about the possibility of `nodenv` managing `brew`-installed node/npm. (Also feel free to tell me it's already supported/easy and I just missed it in the docs 🙏).

A few salient points:

- brew `node` is a dep that ends up coming in with some pretty common packages:
    ```
    $ brew uses node
    azure-cli@1  bower  firebase-cli  grunt-cli  webpack  angular-cli  babel  coffeescript  heroku [...] emscripten  gitter-cli  http-server  jhipster  nativefier  typescript  yarn
    ```
- ... but nodenv ends up either shadowing or being shadowed by `brew`'s path entry.
- It also feels a bit like the `system` versions of `ruby` and `python` that `rbenv` and `pyenv` support: special binary and dependency dirs, and I note that there is no system `node`.
- ...except for one particularly hard-to-introspect path decision: brew installed `node` and `npm` link node CLI scripts/binaries directly into `/usr/local/bin`

I did a very bad, wrong thing here this morning to create and maintain a shadow nodenv `versions` entry for `homebrew` node (shield your eyes!): https://github.com/senorflor/tilde/blob/master/bash/functions/relink_brew_node

Any thoughts on a non-temporary/hacky way to have `nodenv` manage `brew`-installed `node`/`npm`?

Thanks for your consideration, and let me know if you need more info or want to talk through the issues involved here: have some pretty fresh context after morning hacks.

**Comment by jasonkarns** [comment]
So rbenv (and nodenv) don't manage or do anything too special for their `system` runtime. It's essentially just a special case default for "just assume the desired bin is elsewhere in PATH".

I agree that brew-installed node feels like `system`, and indeed, I do treat it that way in my own setups. (I have node installed via homebrew and keep it up to date with latest available.) nodenv works just fine with this setup such that with brew's node available in `PATH`, one can use it as `system`.

Can you provide more explanation on what you mean by:
> brew installed node and npm link node CLI scripts/binaries directly into /usr/local/bin

(I think your homebrew node link was kinda clever.)

**Comment by senorflor** [comment]
Aha! I think I finally understand how to use `system`: thanks for that. I read the docs again and it's also clearer. What I was missing was the initialization step of actually switching to `system` so that it would display in the `nodenv versions` list.

> Can you provide more explanation on what you mean by:
>
> > brew installed node and npm link node CLI scripts/binaries directly into /usr/local/bin

Homebrew sets up `npm`'s prefix to be the same as `homebrew`'s (https://github.com/Homebrew/homebrew-core/blob/b7d1e926e/Formula/node.rb#L109), so that symlinks to npm package binaries/CLI scripts go directly into `/usr/local/bin` instead of some node-only location. This may not be too surprising, guess I'm just working my way towards understanding both `homebrew` and `*`-`env` at the same time. 🐢 

Thanks, Jason!

**Comment by jasonkarns** [comment]
> Homebrew sets up npm's prefix to be the same as homebrew's

Ah, yes. They do this so that upgrading node (via brew) doesn't result in losing all your global node modules.

Node itself expects your global modules to live "within" the node installation (that's the configuration that node ships with by default in their distributions). nodenv itself also practically requires this setup, since it facilitates having numerous versions installed (which implies conflicting major versions which would increase likelihood of global module breakage if global modules were shared between versions).

I have thought about reconciling the way homebrew and nodenv handle global modules somehow, but I don't have any good conclusions yet. :)

Other than perhaps checking out https://github.com/nodenv/nodenv-default-packages or https://github.com/nodenv/nodenv-npm-migrate. The former ensures that each newly installed node automatically installs the configured list of global modules. And the latter will "migrate" all of global modules currently installed in a specified node, to another node version.

Neither of these really do anything regarding linking, but they both facilitate some amount of seamless transitioning of global modules between node versions (as brew's external node_modules directory is intended to do).
