### ISSUE TITLE
Node.js v9.2.0  is not in the list

### ISSUE THREAD

**Issue by webmobiles** [nodenv/nodenv#98]
I've upgrade nodenv, when I do:

nodenv install -l 

the last version that I see is: 9.1.0

I think I must to wait some days more for v9.2.0  ?

**Comment by jasonkarns** [comment]
it's in node-build master but node-build hasn't had a release since then. If you have node-build installed via git, you can get latest by pulling or using nodenv-update plugin. If installed through homebrew, will need to wait for a release and for homebrew to update the formula.

And there's always https://github.com/nodenv/node-build-update-defs to scrape your own build defs regardless what's in node-build.

**Comment by jasonkarns** [comment]
https://github.com/nodenv/node-build/releases/v2.6.19

**Comment by webmobiles** [comment]
I see, i use brew, so I will wait brew will be update. I did not realise nodenv, is independent from brew; thanks
