### ISSUE TITLE
Support semver in .node-version file

### ISSUE THREAD

**Issue by Nevon** [nodenv/nodenv#99]
A project I'm contributing to has the version `^8.8` defined in `.node-version`, but installing the version `8.9.1` does not satisfy that version requirement according to `nodenv`.

```
➜  clients git:(master) ✗ cat ../.node-version
^8.8
➜  clients git:(master) ✗ yarn android:setup
nodenv: version `^8.8' is not installed (set by /Users/tommy.brunn/workspace/app/.node-version)
➜  clients git:(master) ✗ nodenv install 8.9.1
nodenv: /Users/tommy.brunn/.nodenv/versions/8.9.1 already exists
continue with installation? (y/N) N
```

I'm working around this at the moment by copying the 8.9.1 version to `^8.8`, but that's pretty darn dirty.

**Comment by grantila** [comment]
This would also allow for collaboration between `nvm` users and `nodenv` users in the same repo (with a `.node-version` checked in)

**Comment by jasonkarns** [comment]
So, off the bat, @Nevon, instead of copying `8.9.1` to `^8.8`, you'd be better off to just symlink it. This can actually be done via nodenv CLI using [nodenv-aliases](https://github.com/nodenv/nodenv-aliases) plugin. You could directly alias to 8.9.1: `nodenv alias "^8.8" 8.9.1`. But you'd be better off to first build up the automatic semver aliases for 8: `nodenv alias --auto`, which will give you 8 => 8.x => 8.x.y. Then you can `nodenv alias ^8.8 8` to ensure that the ^8.8 alias is always pointing to the highest 8.x release that you have installed. (nodenv-aliases keeps the semver aliases pointing to correct and valid versions as nodes are installed/uninstalled)

And for others who think they want this (related) behavior, you can use [nodenv-aliases](https://github.com/nodenv/nodenv-aliases). This would allow you to set the nodenv-version file to be `8.8`, and nodenv-aliases sets up all the proper semver-compatible symlinks automatically.

But now I'll expound on why this is a bad idea.

When rbenv was first created (and nodenv derives from rbenv), ruby versions were not semver compatible, so doing any fuzzy matching would be dangerous. But more importantly, _even with_ semver compatible runtime versions, it's bad practice to have your runtime switching around under your feet. This is why yarn and npm use lockfiles. (and npm should have had them from the start; see bundler) Neither your deps and _especially_ the underlying runtime should be shifting around without explicit _manual_ instruction to do so. You never know when your code implicitly depends on behavior that is considered a "bug" by the runtime (or any of the thousands of dependencies implicitly depend on some "buggy" behavior). Along comes a new version of node that comes available on your deployment host and suddenly your .node-version file matches a version of node that has never been run by local devs, perhaps never even been run on CI. But it's available on the deployment host and so nodenv picks up the never-vetted runtime and boom: error in production.

Deployments should be locked down to explicit runtime versions just as your dependencies are locked down to explicit versions via the lockfile.
